### ISSUE TITLE
Kamera ist aktiv, Array kann nicht gespeichert werden

### ISSUE THREAD

**Issue by Sarma21** [gkhnrsln/SP1920#6]
Controller Crash mit eventuell veralteter JDK.

**Comment by gkhnrsln** [comment]
Keine Probleme bei mir "Windows" mit OpenJDK 11.0.4. Es stürzt nichts ab. Scheint ein Linux Problem zu sein.

**Comment by Sarma21** [comment]
Kannst du das Array speichern? Bei mir funktioniert es am Mac auch nicht

**Comment by hannes90** [comment]
Mit deinem Code Fehler: controller exited with status: 1.

**Comment by hannes90** [comment]
![Error](https://user-images.githubusercontent.com/45995859/65998074-eafc2380-e49a-11e9-934b-18e9aea260d0.png)

**Comment by gkhnrsln** [comment]
> 
> 
> ![Error](https://user-images.githubusercontent.com/45995859/65998074-eafc2380-e49a-11e9-934b-18e9aea260d0.png)

Du musst deine Java Version am besten aktualisieren. Hast momentan Version 8. Probier 11 zb aus.

**Comment by gkhnrsln** [comment]
> 
> 
> Kannst du das Array speichern? Bei mir funktioniert es am Mac auch nicht

Hast du auch die aktuelle JDK?

**Comment by gkhnrsln** [comment]
Der Fehler ist umgehbar, wenn man vorher eine Motiondatei in der Main Methode ausführt.
